// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package daisyui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/sudeep9/rxui"
	"strings"
)

type CheckboxColor string
type CheckboxSize string

const (
	CheckboxColorNeutral   CheckboxColor = "checkbox-neutral"
	CheckboxColorPrimary   CheckboxColor = "checkbox-primary"
	CheckboxColorSecondary CheckboxColor = "checkbox-secondary"
	CheckboxColorError     CheckboxColor = "checkbox-error"

	CheckboxSizeXtraSmall CheckboxSize = "checkbox-xs"
	CheckboxSizeSmall     CheckboxSize = "checkbox-sm"
	CheckboxSizeMedium    CheckboxSize = "checkbox-md"
	CheckboxSizeLarge     CheckboxSize = "checkbox-lg"
	CheckboxSizeXtraLarge CheckboxSize = "checkbox-xl"
)

type CheckboxProps struct {
	Color CheckboxColor
	Size  CheckboxSize
}

func Checkbox(p CheckboxProps, attrlist ...templ.KeyValue[string, any]) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)

		classes := []string{"checkbox"}
		if p.Color != "" {
			classes = append(classes, string(p.Color))
		}
		if p.Size != "" {
			classes = append(classes, string(p.Size))
		}

		attrs := rxui.MergeClass(strings.Join(classes, " "), attrlist...)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<input type=\"checkbox\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, attrs)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
